version: '3.3'
volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:
  redoc:
  
services:

  foodgram_db:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    env_file: .env.example
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/media/
      - redoc:/app/api/docs/
    depends_on:
      - foodgram_db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
      - foodgram_static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_media:/media/
      - foodgram_static:/static/
    depends_on:
      - backend
      - frontend