# Generated by Django 3.2 on 2023-06-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230622_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
